-- --------------------------------------------------------
-- 호스트:                          bp.ssaverytime.kr
-- 서버 버전:                        10.3.38-MariaDB-0ubuntu0.20.04.1 - Ubuntu 20.04
-- 서버 OS:                        debian-linux-gnu
-- HeidiSQL 버전:                  12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- 프로시저 S08P12D104.MAKE_MAIL_AUTH_NUMBER 구조 내보내기
DELIMITER //
CREATE PROCEDURE `MAKE_MAIL_AUTH_NUMBER`(
	IN `PARAM_EMAIL` VARCHAR(200)
)
BEGIN
	INSERT INTO `S08P12D104`.MWS_MAIL_AUTH VALUES (NULL, PARAM_EMAIL, CONCAT(SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1)
             ), NOW(), DATE_ADD(NOW(), INTERVAL 5 MINUTE), 0);
     SELECT * FROM MWS_MAIL_AUTH WHERE EMAIL = PARAM_EMAIL ORDER BY REG_DT DESC LIMIT 1;
END//
DELIMITER ;

-- 프로시저 S08P12D104.MAKE_SMS_AUTH_NUMBER 구조 내보내기
DELIMITER //
CREATE PROCEDURE `MAKE_SMS_AUTH_NUMBER`(
	IN `PARAM_NUM` VARCHAR(50)
)
BEGIN
	INSERT INTO `S08P12D104`.MWS_SMS_AUTH VALUES(NULL, PARAM_NUM, CONCAT(SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1),
              SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', RAND()*36+1, 1)
             ), NOW(), DATE_ADD(NOW(), INTERVAL 5 MINUTE), 0);
     SELECT * FROM MWS_SMS_AUTH WHERE PHONE_NUM = PARAM_NUM ORDER BY REG_DT DESC LIMIT 1;
END//
DELIMITER ;

-- 테이블 S08P12D104.MWS_ADDRESS 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_ADDRESS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ZIP_NO` varchar(5) DEFAULT NULL COMMENT '우편번호',
  `SIDO` varchar(20) DEFAULT NULL COMMENT '시도',
  `SIDO_ENG` varchar(40) DEFAULT NULL COMMENT '시도(영문)',
  `SIGUNGU` varchar(20) DEFAULT NULL COMMENT '시군구',
  `SIGUNGU_ENG` varchar(40) DEFAULT NULL COMMENT '시군구(영문)',
  `EUPMYUN` varchar(20) DEFAULT NULL COMMENT '읍면',
  `EUPMYUN_ENG` varchar(40) DEFAULT NULL COMMENT '읍면(영문)',
  `DORO_CD` varchar(12) DEFAULT NULL COMMENT '도로명코드',
  `DORO` varchar(80) DEFAULT NULL COMMENT '도로명',
  `DORO_ENG` varchar(80) DEFAULT NULL COMMENT '도로명(영문)',
  `UNDERGROUND_YN` char(1) DEFAULT NULL COMMENT '지하여부',
  `BUILD_NO1` decimal(5,0) DEFAULT NULL COMMENT '건물번호본번',
  `BUILD_NO2` decimal(5,0) DEFAULT NULL COMMENT '건물번호부번',
  `BUILD_NO_MANAGE_NO` varchar(25) DEFAULT NULL COMMENT '건물관리번호',
  `DARYANG_NM` varchar(40) DEFAULT NULL COMMENT '다량배달처명',
  `BUILD_NM` varchar(200) DEFAULT NULL COMMENT '시군구용건물명',
  `DONG_CD` varchar(10) DEFAULT NULL COMMENT '법정동코드',
  `DONG_NM` varchar(20) DEFAULT NULL COMMENT '법정동명',
  `RI` varchar(20) DEFAULT NULL COMMENT '리명',
  `H_DONG_NM` varchar(40) DEFAULT NULL COMMENT '행정동명',
  `SAN_YN` varchar(1) DEFAULT NULL COMMENT '산여부',
  `ZIBUN1` decimal(4,0) DEFAULT NULL COMMENT '지번본번',
  `EUPMYUN_DONG_SN` varchar(2) DEFAULT NULL COMMENT '읍면동일련번호',
  `ZIBUN2` decimal(4,0) DEFAULT NULL COMMENT '지번부번',
  `ZIP_NO_OLD` varchar(4) DEFAULT NULL COMMENT '구우편번호',
  `ZIP_SN` varchar(2) DEFAULT NULL COMMENT '우편일련번호',
  PRIMARY KEY (`ID`),
  KEY `PK_SIDO` (`SIDO`),
  KEY `PK_SIGUNGU` (`SIGUNGU`),
  KEY `PK_SIGUNGU_SIDO` (`SIGUNGU`,`SIDO`),
  KEY `PK_DONG` (`H_DONG_NM`) USING BTREE,
  KEY `PK_DONG_SIGUNGU_SIDO` (`H_DONG_NM`,`SIGUNGU`,`SIDO`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_ADMIN 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_ADMIN` (
  `ID` varchar(50) NOT NULL COMMENT '아이디',
  `PWD` varchar(200) NOT NULL COMMENT '비밀번호',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_ADMIN_LOGIN_LOG 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_ADMIN_LOGIN_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADMIN_ID` varchar(50) NOT NULL,
  `BROWSER` varchar(50) NOT NULL,
  `IP_ADDR` varchar(50) NOT NULL,
  `OS` varchar(50) NOT NULL,
  `REG_DT` datetime NOT NULL COMMENT '로그인 일시',
  PRIMARY KEY (`ID`),
  KEY `FK_ADMIN_ID` (`ADMIN_ID`),
  CONSTRAINT `FK_ADMIN_ID` FOREIGN KEY (`ADMIN_ID`) REFERENCES `MWS_ADMIN` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_BROLLY 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_BROLLY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '우산 고유 번호',
  `NAME` varchar(50) NOT NULL COMMENT '우산 고유 이름',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_BROLLY_CASE 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_BROLLY_CASE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '케이스 고유 번호',
  `NAME` varchar(50) NOT NULL COMMENT '케이스 이름',
  `LAT` double NOT NULL COMMENT '위도',
  `LNG` double NOT NULL COMMENT '경도',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_BROLLY_HOLDER 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_BROLLY_HOLDER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '홀더 고유 번호',
  `NUM` int(11) NOT NULL COMMENT '케이스별 홀더 번호',
  `CASE_ID` int(11) NOT NULL COMMENT '케이스 번호',
  `BROLLY_ID` int(11) DEFAULT NULL COMMENT '우산 번호',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `BROLLY_ID` (`BROLLY_ID`),
  KEY `FK_CASE_ID` (`CASE_ID`),
  CONSTRAINT `FK_BROLLY_ID` FOREIGN KEY (`BROLLY_ID`) REFERENCES `MWS_BROLLY` (`ID`),
  CONSTRAINT `FK_CASE_ID` FOREIGN KEY (`CASE_ID`) REFERENCES `MWS_BROLLY_CASE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_BROLLY_PAY_LOG 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_BROLLY_PAY_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RECEIPT_ID` varchar(200) NOT NULL COMMENT '부트페이 결제 ID',
  `PRICE` int(11) NOT NULL COMMENT '결제금액',
  `USER_ID` varchar(50) NOT NULL COMMENT '사용자 ID',
  `STATUS` varchar(100) NOT NULL COMMENT '결제상태',
  `REG_DT` datetime NOT NULL COMMENT '결제시간',
  `UPT_DT` datetime DEFAULT NULL COMMENT '결제취소시간',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `RECEIPT_ID` (`RECEIPT_ID`),
  KEY `FK_PAY_USER_ID` (`USER_ID`),
  CONSTRAINT `FK_PAY_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `MWS_USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_BROLLY_RENT_LOG 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_BROLLY_RENT_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PAY_ID` int(11) NOT NULL,
  `BROLLY_ID` int(11) NOT NULL COMMENT '우산 고유 번호',
  `CASE_ID` int(11) NOT NULL COMMENT '케이스 고유 번호',
  `USER_ID` varchar(50) NOT NULL COMMENT '사용자 아이디',
  `STATE` tinyint(1) NOT NULL COMMENT '반납 여부',
  `REG_DT` datetime NOT NULL COMMENT '대여 일시',
  `EXP_DT` datetime NOT NULL COMMENT '반납 예정일',
  `UPT_DT` datetime DEFAULT NULL COMMENT '반납 일시',
  `IMG_NAME` varchar(200) DEFAULT NULL COMMENT '우산 반납 사진 파일명',
  `DEPOSITE_MONEY` int(11) NOT NULL COMMENT '보증금',
  `RENT_MONEY` int(11) NOT NULL DEFAULT 0 COMMENT '대여료',
  PRIMARY KEY (`ID`),
  KEY `FK_RENT_BROLLY_ID` (`BROLLY_ID`),
  KEY `FK_RENT_CASE_ID` (`CASE_ID`),
  KEY `FK_RENT_USER_ID` (`USER_ID`),
  KEY `FK_RENT_PAY_ID` (`PAY_ID`),
  CONSTRAINT `FK_RENT_BROLLY_ID` FOREIGN KEY (`BROLLY_ID`) REFERENCES `MWS_BROLLY` (`ID`),
  CONSTRAINT `FK_RENT_CASE_ID` FOREIGN KEY (`CASE_ID`) REFERENCES `MWS_BROLLY_CASE` (`ID`),
  CONSTRAINT `FK_RENT_PAY_ID` FOREIGN KEY (`PAY_ID`) REFERENCES `MWS_BROLLY_PAY_LOG` (`ID`),
  CONSTRAINT `FK_RENT_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `MWS_USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_MAIL_AUTH 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_MAIL_AUTH` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(200) NOT NULL COMMENT '인증 이메일',
  `AUTH_NUM` varchar(50) NOT NULL COMMENT '인증 번호',
  `REG_DT` datetime NOT NULL COMMENT '인증 시간',
  `EXP_DT` datetime NOT NULL COMMENT '만료 시간',
  `STATUS` tinyint(1) NOT NULL COMMENT '인증 여부',
  PRIMARY KEY (`ID`),
  KEY `IDX_AUTH_EMAIL` (`EMAIL`),
  KEY `IDX_AUTH_EMAIL_EXPDT_STATUS` (`EMAIL`,`EXP_DT`,`STATUS`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_PRICE 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_PRICE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DEPOSITE_MONEY` int(11) NOT NULL COMMENT '보증금',
  `MONEY` int(11) NOT NULL COMMENT '시간당 대여금액',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_QUESTION 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_QUESTION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(200) NOT NULL,
  `CONTENT` text NOT NULL,
  `USER_ID` varchar(50) NOT NULL,
  `REG_DT` datetime NOT NULL,
  `UPT_DT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_QUESTION_USER_ID` (`USER_ID`),
  CONSTRAINT `FK_QUESTION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `MWS_USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_SMS_AUTH 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_SMS_AUTH` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHONE_NUM` varchar(50) NOT NULL COMMENT '인증 이메일',
  `AUTH_NUM` varchar(50) NOT NULL COMMENT '인증 번호',
  `REG_DT` datetime NOT NULL COMMENT '인증 시간',
  `EXP_DT` datetime NOT NULL COMMENT '만료 시간',
  `STATUS` tinyint(1) NOT NULL COMMENT '인증 여부',
  PRIMARY KEY (`ID`),
  KEY `IDX_AUTH_PHONENUM` (`PHONE_NUM`),
  KEY `IDX_AUTH_PHONENUM_EXPDT_STATUS` (`PHONE_NUM`,`EXP_DT`,`STATUS`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_TERMS 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_TERMS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTENT` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_USER 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_USER` (
  `ID` varchar(50) NOT NULL COMMENT '아이디',
  `PWD` varchar(200) NOT NULL COMMENT '비밀번호',
  `NAME` varchar(50) NOT NULL COMMENT '이름',
  `PHONE_NUM` varchar(50) NOT NULL COMMENT '휴대전화 번호',
  `SIDO` varchar(50) NOT NULL COMMENT '시도',
  `SIGUNGU` varchar(50) NOT NULL COMMENT '시군구',
  `DONG` varchar(50) NOT NULL COMMENT '동',
  `EMAIL` varchar(200) NOT NULL COMMENT '이메일',
  `REG_DT` datetime NOT NULL COMMENT '가입 날짜',
  `EXP_DT` datetime DEFAULT NULL COMMENT '탈퇴 날짜',
  `ACTIVE_STATE` tinyint(1) NOT NULL COMMENT '계정 활성화 여부 (0: 탈퇴, 1: 미탈퇴)',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P12D104.MWS_USER_LOGIN_LOG 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_USER_LOGIN_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(50) NOT NULL,
  `BROWSER` varchar(50) NOT NULL,
  `IP_ADDR` varchar(50) NOT NULL,
  `OS` varchar(50) NOT NULL,
  `REG_DT` datetime NOT NULL COMMENT '로그인 일시',
  PRIMARY KEY (`ID`),
  KEY `FK_USER_ID` (`USER_ID`),
  CONSTRAINT `FK_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `MWS_USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 프로시저 S08P12D104.UPDATE_RENT_OVERDUE 구조 내보내기
DELIMITER //
CREATE PROCEDURE `UPDATE_RENT_OVERDUE`()
BEGIN
	SELECT MBRL.USER_ID as userId, MU.EMAIL as email 
	FROM MWS_BROLLY_RENT_LOG MBRL 
	INNER JOIN MWS_USER MU
	ON MBRL.USER_ID = MU.ID
	WHERE TIMESTAMPDIFF(MINUTE,NOW(),MBRL.EXP_DT) <= 0 AND MBRL.STATE = 0;
	
	UPDATE MWS_BROLLY_RENT_LOG 
	SET STATE = 1, UPT_DT = NOW(), RENT_MONEY = (SELECT DEPOSITE_MONEY FROM MWS_PRICE WHERE ID = 1) 
	WHERE TIMESTAMPDIFF(MINUTE,NOW(),EXP_DT) <= 0 AND STATE = 0;
END//
DELIMITER ;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
